In [2]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests
# Import the API key.
from config import g_key

In [3]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/cities.csv")
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Albany,US,2020-04-18 17:19:48,42.60,-73.97,42.01,75,98,3.00
1,1,Bilibino,RU,2020-04-18 17:16:20,68.05,166.44,-8.21,81,13,5.03
2,2,Mataura,NZ,2020-04-18 17:19:49,-46.19,168.86,44.01,93,100,3.00
3,3,Rikitea,PF,2020-04-18 17:19:49,-23.12,-134.97,76.78,70,1,4.68
4,4,Georgetown,MY,2020-04-18 17:18:22,5.41,100.34,82.40,88,20,4.70

In [4]:
city_data_df.dtypes

City_ID         int64
City           object
Country        object
Date           object
Lat           float64
Lng           float64
Max Temp      float64
Humidity        int64
Cloudiness      int64
Wind Speed    float64
dtype: object

In [8]:
# Heatmap of temperature
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)
#get the latitude and longitude
locations = city_data_df[["Lat", "Lng"]]
#get the maximum temperature
max_temp = city_data_df["Max Temp"]

#Remove negative max temperatures with if loop - commented 
#temps = []
#for temp in max_temp:
#    temps.append(max(temp, 0))
# Assign the figure variable.
#fig = gmaps.figure()
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
# Assign the heatmap variable (base version commented below)
# heat_layer = gmaps.heatmap_layer(locations, weights=temps)
#heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in max_temp])
heat_layer = gmaps.heatmap_layer(locations, weights=temps, dissipating=False, max_intensity=300, point_radius=4)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [9]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
humidity = city_data_df["Humidity"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [11]:
# Heatmap of percent cloudiness
locations = city_data_df[["Lat", "Lng"]]
cloudiness = city_data_df["Cloudiness"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=cloudiness, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [12]:
# Heatmap of percent wind speed
locations = city_data_df[["Lat", "Lng"]]
wind = city_data_df["Wind Speed"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=wind, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [13]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [14]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
3,3,Rikitea,PF,2020-04-18 17:19:49,-23.12,-134.97,76.78,70,1,4.68
4,4,Georgetown,MY,2020-04-18 17:18:22,5.41,100.34,82.40,88,20,4.70
8,8,Butaritari,KI,2020-04-18 17:19:51,3.07,172.79,82.04,78,98,14.43
13,13,San Patricio,MX,2020-04-18 17:19:54,19.22,-104.70,82.40,78,20,8.05
20,20,Port Hedland,AU,2020-04-18 17:19:57,-20.32,118.57,80.60,94,67,9.17
22,22,Atuona,PF,2020-04-18 17:19:59,-9.80,-139.03,82.26,79,63,14.20
23,23,Cayenne,GF,2020-04-18 17:15:49,4.93,-52.33,84.20,79,20,6.93
25,25,Ahuimanu,US,2020-04-18 17:20:00,21.44,-157.84,78.80,57,20,9.17
29,29,Manggar,ID,2020-04-18 17:20:02,-2.88,108.27,81.36,75,98,2.08
31,31,Vega De Alatorre,MX,2020-04-18 17:20:03,20.03,-96.63,83.37,75,53,6.06

In [16]:
preferred_cities_df.count()

City_ID       180
City          180
Country       178
Date          180
Lat           180
Lng           180
Max Temp      180
Humidity      180
Cloudiness    180
Wind Speed    180
dtype: int64

In [18]:
preferred_cities_df_adj=preferred_cities_df.dropna()
preferred_cities_df_adj

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
3,3,Rikitea,PF,2020-04-18 17:19:49,-23.12,-134.97,76.78,70,1,4.68
4,4,Georgetown,MY,2020-04-18 17:18:22,5.41,100.34,82.40,88,20,4.70
8,8,Butaritari,KI,2020-04-18 17:19:51,3.07,172.79,82.04,78,98,14.43
13,13,San Patricio,MX,2020-04-18 17:19:54,19.22,-104.70,82.40,78,20,8.05
20,20,Port Hedland,AU,2020-04-18 17:19:57,-20.32,118.57,80.60,94,67,9.17
...,...,...,...,...,...,...,...,...,...,...
539,539,Kloulklubed,PW,2020-04-18 17:24:05,7.04,134.26,83.12,80,100,15.57
540,540,Demak,ID,2020-04-18 17:24:48,-6.89,110.64,79.03,80,100,2.66
546,546,Wad Rawah,SD,2020-04-18 17:24:50,15.16,33.14,86.22,12,87,11.43
547,547,Aloleng,PH,2020-04-18 17:24:51,16.13,119.78,81.45,77,61,6.44
548,548,Santana Do Livramento,BR,2020-04-18 17:24:51,-30.89,-55.53,77.45,34,0,7.74

In [20]:
#create dataframe hotel_df to store hotel names along with city, country, max temp, and coordinates
hotel_df = preferred_cities_df_adj[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df

                      City Country  Max Temp    Lat     Lng Hotel Name
3                  Rikitea      PF     76.78 -23.12 -134.97
4               Georgetown      MY     82.40   5.41  100.34
8               Butaritari      KI     82.04   3.07  172.79
13            San Patricio      MX     82.40  19.22 -104.70
20            Port Hedland      AU     80.60 -20.32  118.57
..                     ...     ...       ...    ...     ...        ...
539            Kloulklubed      PW     83.12   7.04  134.26
540                  Demak      ID     79.03  -6.89  110.64
546              Wad Rawah      SD     86.22  15.16   33.14
547                Aloleng      PH     81.45  16.13  119.78
548  Santana Do Livramento      BR     77.45 -30.89  -55.53

[178 rows x 6 columns]

In [35]:
# Set the parameters to search for a hotel in Paris.
params = {
    "radius": 5000,
    "types": "lodging",
    "key": g_key,
    "location": "48.8566, 2.3522"}
# Use base URL to search for hotels in Paris.
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
# Make request and get the JSON data from the search.
hotels = requests.get(base_url, params=params).json()
hotels

{'html_attributions': [],
 'next_page_token': 'CqQCHAEAAFGbVPYI7W2CAuf98I4k0J1ZrzQxaApn1W7GYA1tHLZOGKGGd6akrZ11nKSgxL2Klu-tNkQQDdRnoNs6o9HVHAMrUlGiVbb6UtHRDLgghLvUuy37BNt0LLKjs4TNsm5ujzLMr1cAm6Kl37W05MYQ952MhVLA2-Lq6Toc-TBeFeq_od-xzqNtEa_g_yZVHiWAK_wUrM6OLWfzrcGn1dIQLxMPy9uuXsX3GQSO_uBMJo2KyyKiyMjThPrU1VgsCZNK9dO310YOg9Xja6ffTUG2eKP9NzsRY9mtAfvJcWarAsR6Ad_8wK5zgqON5gEc9jjVk5mHSv7_i4RlQvVF_Om9B1iph9n58Xb3Tp38B27IelMjT4UEeKd1pw6TN_mj988B1xIQplH7DsyXxi_Ikd3BvnMJbBoUvnTSKdtt6slNLgjgtYNH0bFMnWg',
 'results': [{'geometry': {'location': {'lat': 48.8581126, 'lng': 2.3529277},
    'viewport': {'northeast': {'lat': 48.8594402302915,
      'lng': 2.354348530291502},
     'southwest': {'lat': 48.8567422697085, 'lng': 2.351650569708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
   'id': '7fa47cb61d7345cecc3b802d0e04fcff2b3d5ecb',
   'name': 'Hôtel Duo',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 3840,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/107554201425443337224">Hôtel Duo</a>'],
     'photo_reference': 'CmRaAAAASmhkU2lqXptKycHGGMN90ZSEoXTLclA0Pm4bd19KfXwrXcTHPjYMGjO-qy7hGhu6qAtpWFo-CX-q2Dv39E42fdW1tWbmgVz8kSXCwzwe6HRyr4SeTd1yaYLa92q_sgLNEhBJmVcGfksQfXf84JbBzL0ZGhSlrs-TeeD7B4zJVVmL1s_embSOdg',
     'width': 5760}],
   'place_id': 'ChIJWU9CqB1u5kcR5P1F2SMoJmc',
   'plus_code': {'compound_code': 'V953+65 Paris, France',
    'global_code': '8FW4V953+65'},
   'rating': 4.2,
   'reference': 'ChIJWU9CqB1u5kcR5P1F2SMoJmc',
   'scope': 'GOOGLE',
   'types': ['night_club',
    'spa',
    'lodging',
    'bar',
    'gym',
    'health',
    'point_of_interest',
    'establishment'],
   'user_ratings_total': 268,
   'vicinity': '11 Rue du Temple, Paris'},
  {'geometry': {'location': {'lat': 48.8582861, 'lng': 2.3464944},
    'viewport': {'northeast': {'lat': 48.8595495802915,
      'lng': 2.347780980291502},
     'southwest': {'lat': 48.8568516197085, 'lng': 2.345083019708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
   'id': '4d2e3fa9d12bf9feb685e628eaa4da9b180956a9',
   'name': 'Hôtel Britannique - Paris Louvre',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 1426,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/108984000175492464929">Hôtel Britannique - Paris Louvre</a>'],
     'photo_reference': 'CmRaAAAAlch2Hi4TLy89Jv99aCOAcO_ycQZChPmi6xRxk9teNGikc5vxPtGO0tKQq-V6c3ATLmslscp_Kd0W9AysCbKlXjVoXyq9g5rZBast9qv_MsZxkzjqmF-uDEfbiQU9hAfLEhCqkmBG9gvLfX7V83hi8lmGGhQH7n7nYI77DLh31M4w35fQvjmgBQ',
     'width': 1476}],
   'place_id': 'ChIJ-4Siox9u5kcRm9vM6DcMXyU',
   'plus_code': {'compound_code': 'V85W+8H Paris, France',
    'global_code': '8FW4V85W+8H'},
   'rating': 4.5,
   'reference': 'ChIJ-4Siox9u5kcRm9vM6DcMXyU',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 240,
   'vicinity': '20 Avenue Victoria, Paris'},
  {'geometry': {'location': {'lat': 48.8606655, 'lng': 2.3469293},
    'viewport': {'northeast': {'lat': 48.8617681302915,
      'lng': 2.348040180291502},
     'southwest': {'lat': 48.8590701697085, 'lng': 2.345342219708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
   'id': '9f68a76d7e95a1f94ca131a0511bfe5ffa306818',
   'name': 'Citadines Les Halles Paris (Apart Hotel Paris)',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 496,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/102565262508115704337">Citadines Les Halles Paris (Apart Hotel Paris)</a>'],
     'photo_reference': 'CmRaAAAARmNTMt0FLvyHfOiW_3R6uSY1jLqGXMJGU6q6MLf0PUQeUcgpdZP0iez51Z2bU0F4UyR96_6z4O7f5jSDD0ssREvX4uzjSz2Ww-mewZ1dOQ_3MShN0l_mkYtAUTyPkxGQEhD3aY5ftyijXkSBBbaI8sA4GhTRy1-YZjff7XZfor7la5sAspuYIA',
     'width': 745}],
   'place_id': 'ChIJQ_QDrxhu5kcRJzNxLLEOSfU',
   'plus_code': {'compound_code': 'V86W+7Q Paris, France',
    'global_code': '8FW4V86W+7Q'},
   'rating': 4.1,
   'reference': 'ChIJQ_QDrxhu5kcRJzNxLLEOSfU',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 787,
   'vicinity': '4 Rue des Innocents, Paris'},
  {'geometry': {'location': {'lat': 48.86034799999999, 'lng': 2.344054},
    'viewport': {'northeast': {'lat': 48.8616503302915,
      'lng': 2.345521080291502},
     'southwest': {'lat': 48.8589523697085, 'lng': 2.342823119708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
   'id': '071875f44126b9c8284f24b598fdfce0ef2b15a8',
   'name': 'Hôtel Ducs de Bourgogne',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 1842,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/101411638353598558320">Best Western Premier Ducs de Bourgogne</a>'],
     'photo_reference': 'CmRaAAAAMk6bSD1CN6q-LOhVjfxzPHDobAp5MyeiCC4u4I9vClCRPR4D5z7_LGANGZfbdKQz3QTCiq2vbAXrpXbuXlBUBi9t9BZNLlvzyQDymK5Ka6ls7G7oElJelAkVYYPaFliUEhAyR3DTq8FTVgC8_WScAcvDGhRP1iuen2cs4387O4PWAdihZ9Yn6A',
     'width': 2880}],
   'place_id': 'ChIJifTG5yFu5kcRdnisbwxnAx4',
   'plus_code': {'compound_code': 'V86V+4J Paris, France',
    'global_code': '8FW4V86V+4J'},
   'rating': 4.5,
   'reference': 'ChIJifTG5yFu5kcRdnisbwxnAx4',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 264,
   'vicinity': '19 Rue du Pont Neuf, Paris'},
  {'geometry': {'location': {'lat': 48.8555091, 'lng': 2.3408736},
    'viewport': {'northeast': {'lat': 48.8569042302915,
      'lng': 2.342317580291502},
     'southwest': {'lat': 48.8542062697085, 'lng': 2.339619619708499}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
   'id': 'da46237a58939495edf652bdf976bd44df477f05',
   'name': 'Citadines Saint-Germain-des-Prés Paris',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 3024,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/116649065792056265685">Gilsun LEE</a>'],
     'photo_reference': 'CmRaAAAAc_cF8jwKaBD_EMGGtKvhaKnt5R09FbwnpwTWnwO_iw2ggFKmRz-Aws385Ed2cEz37J-PtAmcj25JpcF2HZC2J_1cLGsue_NiFkzjxfbWgFU-YbDeYwOkt_PuOeqwkDkhEhD4YMC-X0klHQptaU9npL8cGhSXKIZpEgPrCVwQ0lwVhB1E04bEvg',
     'width': 4032}],
   'place_id': 'ChIJo5pYcN9x5kcRERXdocMgqmE',
   'plus_code': {'compound_code': 'V84R+68 Paris, France',
    'global_code': '8FW4V84R+68'},
   'rating': 4.3,
   'reference': 'ChIJo5pYcN9x5kcRERXdocMgqmE',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 638,
   'vicinity': '53 ter Quai des Grands Augustins, Paris'},
  {'geometry': {'location': {'lat': 48.86634659999999, 'lng': 2.36064},
    'viewport': {'northeast': {'lat': 48.8677623302915,
      'lng': 2.361952180291502},
     'southwest': {'lat': 48.86506436970851, 'lng': 2.359254219708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
   'id': '87ab2d184ee12f6be846d60470ed800629c99521',
   'name': 'Paris France Hôtel',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 2673,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/102332962500946068613">Paris France Hôtel</a>'],
     'photo_reference': 'CmRaAAAAvCOmhfoI5wK6AY_IUUTe9rw2y4aSEy7XDNY2fddh1nAfzEuMwvR7asbe1dNKDN0KHD2uIeR5UqvSas-ueFwprB5mfsYilO-3Tx5QjNuwcdrKNQLqv0XZFZHEDkexdSLzEhDoWvDtPk8GvudChm2nJs4DGhRG99Ol_cadzUDI2EDup7VhQCawZg',
     'width': 3463}],
   'place_id': 'ChIJhXWLZg9u5kcRDVyqoZYgcmg',
   'plus_code': {'compound_code': 'V986+G7 Paris, France',
    'global_code': '8FW4V986+G7'},
   'rating': 4.3,
   'reference': 'ChIJhXWLZg9u5kcRDVyqoZYgcmg',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 363,
   'vicinity': '72 Rue de Turbigo, Paris'},
  {'geometry': {'location': {'lat': 48.8549629, 'lng': 2.3331998},
    'viewport': {'northeast': {'lat': 48.8563231802915,
      'lng': 2.334450380291502},
     'southwest': {'lat': 48.8536252197085, 'lng': 2.331752419708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
   'id': 'd466793620469a720b439cf769a6f4c28217ef88',
   'name': 'Hôtel Bel Ami',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 4377,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/111426311500153571368">Hôtel Bel Ami</a>'],
     'photo_reference': 'CmRaAAAA2-CNwBqQKSLLLrVlOxHxs-uzA0MYXEIOK-Sng4qNP_x7-FsWUBoiUNxzj427fgNvph3muOlTbBgNTs_fL21OL8eEDuitWWa4VPWTiGvjVwREYgwFvncxfwZYk2SHq1zeEhCErpU5AMKH1DokqrUF92X_GhQMafjJeMKEdC32FiJg7U_p_EpjJA',
     'width': 6566}],
   'place_id': 'ChIJj0jPiddx5kcRnYv-p3-vfCA',
   'plus_code': {'compound_code': 'V83M+X7 Paris, France',
    'global_code': '8FW4V83M+X7'},
   'rating': 4.6,
   'reference': 'ChIJj0jPiddx5kcRnYv-p3-vfCA',
   'scope': 'GOOGLE',
   'types': ['spa',
    'lodging',
    'bar',
    'restaurant',
    'food',
    'point_of_interest',
    'establishment'],
   'user_ratings_total': 446,
   'vicinity': '7 Rue Saint-Benoît, Paris'},
  {'geometry': {'location': {'lat': 48.86386539999999, 'lng': 2.3325488},
    'viewport': {'northeast': {'lat': 48.8650759802915,
      'lng': 2.333775730291502},
     'southwest': {'lat': 48.8623780197085, 'lng': 2.331077769708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
   'id': '20dd8ae8d6ad9bbbe4ea9c6caf623fa071be187f',
   'name': 'Hotel Regina Louvre',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 2828,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/109066439891801774697">Hotel Regina Louvre</a>'],
     'photo_reference': 'CmRaAAAA9kvP34rj2cuIuo3hBadMfbjGwpGWHJG85xghsOsU-3l6vLE8K-U7xWX5MAZpkPAmC0W6burQv8g-4pRnjPlFjfduButK94smvvWwND7eJhSpJZHaQyiZ7ZO0AQ0Qi6LREhAD-gS4odHAFAgbPdiuWHHDGhSkHmI6URWk9rSjpbGeQwirRidaWg',
     'width': 4242}],
   'place_id': 'ChIJP_-HCS9u5kcRsj9b1x7Pl8w',
   'plus_code': {'compound_code': 'V87M+G2 Paris, France',
    'global_code': '8FW4V87M+G2'},
   'rating': 4.5,
   'reference': 'ChIJP_-HCS9u5kcRsj9b1x7Pl8w',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 493,
   'vicinity': '2 Place des Pyramides, Paris'},
  {'geometry': {'location': {'lat': 48.84756770000001, 'lng': 2.3718501},
    'viewport': {'northeast': {'lat': 48.8488975302915,
      'lng': 2.373108630291501},
     'southwest': {'lat': 48.8461995697085, 'lng': 2.370410669708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
   'id': 'dd8abb1bc4b1337fc3bd3f26e92d36c9a31de2fd',
   'name': 'Hôtel De France Gare de Lyon Bastille',
   'photos': [{'height': 787,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/117462031751048846575">Hôtel De France Gare de Lyon Bastille</a>'],
     'photo_reference': 'CmRaAAAA9WMxyJBiBmp69TCW8oP_1XZVLzQlDmIX-Plbuy7WvWjngHlKAUdirUDD45MBqCA8m24xfeGjrNLDiSIcmY0ji5oIaTCTFW3B0y4QDuRpEPUtBW2o8oRLRXFawKzxo_xBEhDS-IFCcbFRBPytssufQTfVGhRxytHMFynx5Jw0GE1fzc80vcwx4Q',
     'width': 1181}],
   'place_id': 'ChIJz6DBYgNy5kcRhOu1LhDIECM',
   'plus_code': {'compound_code': 'R9XC+2P Paris, France',
    'global_code': '8FW4R9XC+2P'},
   'rating': 3.3,
   'reference': 'ChIJz6DBYgNy5kcRhOu1LhDIECM',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 374,
   'vicinity': '12 Rue de Lyon, Paris'},
  {'geometry': {'location': {'lat': 48.8717386, 'lng': 2.3447052},
    'viewport': {'northeast': {'lat': 48.8731394302915,
      'lng': 2.346067130291502},
     'southwest': {'lat': 48.8704414697085, 'lng': 2.343369169708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
   'id': '78d0f620a6cdf990371302f25505f3916839f53a',
   'name': 'Hôtel Corona Opéra',
   'photos': [{'height': 2592,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/102510876010964977166">武石日登美</a>'],
     'photo_reference': 'CmRaAAAAyvQF_y4HHhSEN1y2udHb9kLX3NSpb89AFDaQ7PNHsfTPoU5ORUiJfU1V-CoR-ZB6BumpCpNvCvF5zCQvv8G2Fx9hNmXuR9KiUo3CBsb3zooHzIbsNC_QgQ-Hsls8rRJPEhAt9TO_YqZnxBnbCO62YK51GhSA2NGKai2DPhsMUGibk-R0G5Iiig',
     'width': 4608}],
   'place_id': 'ChIJ8e3Qcj5u5kcR2MIGwNxustk',
   'plus_code': {'compound_code': 'V8CV+MV Paris, France',
    'global_code': '8FW4V8CV+MV'},
   'rating': 4,
   'reference': 'ChIJ8e3Qcj5u5kcR2MIGwNxustk',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 304,
   'vicinity': '8 Cité Bergère, Paris'},
  {'geometry': {'location': {'lat': 48.8423474, 'lng': 2.3632229},
    'viewport': {'northeast': {'lat': 48.8436522302915,
      'lng': 2.364706330291502},
     'southwest': {'lat': 48.8409542697085, 'lng': 2.362008369708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
   'id': 'c2c8e3f55bda0fd2bec95cd85db83c756bfebe2c',
   'name': 'Hôtel Libertel Austerlitz Jardin des Plantes',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 683,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/113748802076686483057">Hôtel Libertel Austerlitz Jardin des Plantes</a>'],
     'photo_reference': 'CmRaAAAAwBZjKF8hCFcpHA7Q_CqIpuwPgY1l5PYgTdTF8KBCmMaPAJDz0S-NVhrjPMpsrI-PkHW1-dqDVwc2zQzConRtQTXtcSa4GnI9IXtbhYo6D99Trd4hqUBR3ZG7IxeKd1r6EhCKaY9VxEp5i9vy1d_NNX4iGhQAMRXmJIJlP7bmMUZxn-ISfR3TGg',
     'width': 1024}],
   'place_id': 'ChIJe-udXPZx5kcRKURHNFv5BSw',
   'plus_code': {'compound_code': 'R9R7+W7 Paris, France',
    'global_code': '8FW4R9R7+W7'},
   'rating': 3.9,
   'reference': 'ChIJe-udXPZx5kcRKURHNFv5BSw',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 413,
   'vicinity': "12 Boulevard de l'Hôpital, Paris"},
  {'geometry': {'location': {'lat': 48.864294, 'lng': 2.3307997},
    'viewport': {'northeast': {'lat': 48.8655772302915,
      'lng': 2.332153880291502},
     'southwest': {'lat': 48.8628792697085, 'lng': 2.329455919708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
   'id': '50797fba20cc1e735c57820607b18b04abf162b9',
   'name': 'Saint James Albany Paris Hôtel Spa',
   'photos': [{'height': 650,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/108570400659068256718">Saint James Albany Paris Hôtel Spa</a>'],
     'photo_reference': 'CmRaAAAA-AtYUSloqyI-MU0qmgmkUiWWHsxmZ68rjHUcScNC9tythKsffWwtxusN1fwKqC8uVA3_MztTPlX6fnzAoaoC4uS-p3zG9gOcKzyElNtwzMs7NqWbsuc8w-0kU4OX_v2bEhDEsljJSFenR4UZcgLhjJqUGhQpmoNNrTmePdjH5askWSVlb2d46Q',
     'width': 802}],
   'place_id': 'ChIJ8znTVS5u5kcREq8TmzOICFs',
   'plus_code': {'compound_code': 'V87J+P8 Paris, France',
    'global_code': '8FW4V87J+P8'},
   'rating': 4,
   'reference': 'ChIJ8znTVS5u5kcREq8TmzOICFs',
   'scope': 'GOOGLE',
   'types': ['spa',
    'lodging',
    'bar',
    'restaurant',
    'food',
    'point_of_interest',
    'establishment'],
   'user_ratings_total': 1068,
   'vicinity': '202 Rue de Rivoli, Paris'},
  {'geometry': {'location': {'lat': 48.87110329999999, 'lng': 2.3389728},
    'viewport': {'northeast': {'lat': 48.87241758029149,
      'lng': 2.340357630291502},
     'southwest': {'lat': 48.8697196197085, 'lng': 2.337659669708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
   'id': 'ef15575a5c2adf57431313a0af490a78350630a5',
   'name': 'Hôtel Icône',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 1066,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/108137830440312077288">Hôtel Icône</a>'],
     'photo_reference': 'CmRaAAAAPOaePnCfi5mKsFqvOijQWJPCjALAliJLeAUd0emN3GqYAPYmo2OO0IeiBeisvSFl8CNQTeaLNy4Aaw7g6o46iVf3ktsx87gLy7CIGKCfiQK1_FFvGsaQJRXzVBq5dqk-EhADK_8uik0D-Wgwf9hhG_reGhRaH-HS_790C7Gem-6kqlUMRRFK6w',
     'width': 1600}],
   'place_id': 'ChIJpQvq5Dtu5kcR0COam2f7v_I',
   'plus_code': {'compound_code': 'V8CQ+CH Paris, France',
    'global_code': '8FW4V8CQ+CH'},
   'rating': 3.7,
   'reference': 'ChIJpQvq5Dtu5kcR0COam2f7v_I',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 134,
   'vicinity': "4 Rue d'Amboise, Paris"},
  {'geometry': {'location': {'lat': 48.86038899999999, 'lng': 2.323112},
    'viewport': {'northeast': {'lat': 48.8617804302915,
      'lng': 2.324489280291502},
     'southwest': {'lat': 48.8590824697085, 'lng': 2.321791319708499}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
   'id': '7f368d30dd657e11d235029a91f97fb176c9bc9a',
   'name': "Hôtel 4 étoiles d'Orsay Paris 7ème - Esprit de France",
   'opening_hours': {'open_now': True},
   'photos': [{'height': 4618,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/117095582791768771344">Baptiste Bazoge</a>'],
     'photo_reference': 'CmRaAAAAUpbhCmClA6l0s1AqKkF96idECCzMnAAH6Owyp8FCworg5mI8fpFCs28LIFtq0ImKOBdhcRSqe9odio5qUYNl_KmlB32l-ce65xcDI_kPURMqfpbQ1Ip136NSO3my7yoHEhAAHDCDFCoFOrvaEFDMw8kzGhRU0IWFu45KXtr192kwnKebXZBhAQ',
     'width': 3464}],
   'place_id': 'ChIJu39_OCtu5kcRWVQ7SFa0J-k',
   'plus_code': {'compound_code': 'V86F+56 Paris, France',
    'global_code': '8FW4V86F+56'},
   'rating': 4.6,
   'reference': 'ChIJu39_OCtu5kcRWVQ7SFa0J-k',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 207,
   'vicinity': '93 Rue de Lille, Paris'},
  {'geometry': {'location': {'lat': 48.8661363, 'lng': 2.3260648},
    'viewport': {'northeast': {'lat': 48.8674534302915,
      'lng': 2.327513280291502},
     'southwest': {'lat': 48.8647554697085, 'lng': 2.324815319708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
   'id': '3706e8da44cbce856612cc5e666bd4e25076a0d8',
   'name': 'Hôtel Mayfair Paris',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 1365,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/113789389085635834164">Hôtel Mayfair Paris</a>'],
     'photo_reference': 'CmRaAAAA3iIspneXNvqnGwkN0pzdOV_M3VCFgipVhVNyVGP52lrPbd4BP4OiMXhsQH5D9diIdwaArYdpRbYFRJg-YEg9WVdcWi1n8K6rhond-j012j0rOJo_r9dNvgkmqumz5xKHEhDpCnLsg9-9zjFA_xA8dV-3GhQKOD2KKuJYBWSTY3_3xWxjxD8ECg',
     'width': 2048}],
   'place_id': 'ChIJTXVIhS1u5kcRlm9-RG0srQs',
   'plus_code': {'compound_code': 'V88G+FC Paris, France',
    'global_code': '8FW4V88G+FC'},
   'rating': 4.2,
   'reference': 'ChIJTXVIhS1u5kcRlm9-RG0srQs',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 245,
   'vicinity': '3 Rue Rouget de Lisle, Paris'},
  {'geometry': {'location': {'lat': 48.8758937, 'lng': 2.3591167},
    'viewport': {'northeast': {'lat': 48.8772989802915,
      'lng': 2.360423530291502},
     'southwest': {'lat': 48.8746010197085, 'lng': 2.357725569708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
   'id': '243057f371f2061f228c750901650cd7fb66d5e3',
   'name': "Holiday Inn Paris - Gare de l'Est",
   'opening_hours': {'open_now': True},
   'photos': [{'height': 1366,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/102027969916801631519">Holiday Inn Paris - Gare de l&#39;Est</a>'],
     'photo_reference': 'CmRaAAAAcZvSerc_Qmyl1QhfkTDGcimESUR4T1LqKZZPi24r-_6Cu8U4tGFidED1btxaJ-eAUJZ2CSXEmDeXmPxjrZj07jTSDqQa0CD-v-U8sqmJQCXnWz-tw_WCUT0yBIAhLmhGEhCXGKLuQTBzWqYmm3T3ZPCsGhS9ytv2tdkjQh0hpniK2_HhyuufZA',
     'width': 2048}],
   'place_id': 'ChIJwUHJSg1u5kcRhNqw_oQNeKI',
   'plus_code': {'compound_code': 'V9G5+9J Paris, France',
    'global_code': '8FW4V9G5+9J'},
   'rating': 3.8,
   'reference': 'ChIJwUHJSg1u5kcRhNqw_oQNeKI',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 1517,
   'vicinity': '45 Rue du 8 Mai 1945 5, Paris'},

In [36]:
len(hotels["results"])

20

In [39]:
#iterate through dataframe
for index, row in hotel_df.iterrows():
    #get latitude and longitude
    lat = row["Lat"]
    lng = row["Lng"]

    #add the latitude and longitude to location key for the params dictionary in gmaps
    params["location"] = f"{lat},{lng}"
    #use search term "lodging" and latitude and longitude
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    #Method_1 get first hotel from results and store name (no check for IndexError) - commented below
    #hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
        #Method_2 get first hotel from results and store name (use try_except check for IndexError)
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [40]:
hotel_df

,City,Country,Max Temp,Lat,Lng,Hotel Name
3,Rikitea,PF,76.78,-23.12,-134.97,Pension Maro'i
4,Georgetown,MY,82.40,5.41,100.34,Cititel Penang
8,Butaritari,KI,82.04,3.07,172.79,Isles Sunset Lodge
13,San Patricio,MX,82.40,19.22,-104.70,Hotel Cabo Blanco
20,Port Hedland,AU,80.60,-20.32,118.57,The Esplanade Hotel
...,...,...,...,...,...,...
539,Kloulklubed,PW,83.12,7.04,134.26,Storyboard Beach Resort
540,Demak,ID,79.03,-6.89,110.64,Inayah Kost
546,Wad Rawah,SD,86.22,15.16,33.14,ود الترابي
547,Aloleng,PH,81.45,16.13,119.78,
548,Santana Do Livramento,BR,77.45,-30.89,-55.53,Hotel Emirates

In [41]:
#add heatmap of temperature for the vacation spots
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False,
             max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
#call figure to plot the data
fig

Figure(layout=FigureLayout(height='420px'))

In [44]:
#add heatmap of temperature for vacation spots and marker for each city
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
#call the figure to plot data
fig

Figure(layout=FigureLayout(height='420px'))

In [45]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [46]:
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))